### ISSUE TITLE
loadParsedGraphs should pay attention to redirects

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-web-client#5]
https://github.com/solid/solid-web-client/blob/6d582c556b0576ccd2b0a39ae8dad19ea4ae58cb/src/client.js#L157
it should use response.url instead of url of initial request
currently if redirected `graph.uri` ends up with a different value than `.why` of all the statements in `.graph.value`

**Comment by dmitrizagidulin** [comment]
Agreed, yeah.

**Comment by elf-pavlik** [comment]
I'll make PR based on https://github.com/elf-pavlik/solid-web-client/commit/192c26423b225047f1b092f546916ec653aa9b68 after #7 gets merged
