### ISSUE TITLE
solidResonse.url should always have full IRI

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-web-client#6]
if someone needs just the paths or relative IRI, helper methods can provide it based on full IRI but not the other way!

**Comment by elf-pavlik** [comment]
https://github.com/solid/solid-web-client/blob/master/src/models/response.js#L122

``` js
  this.url = xhrResponse.getResponseHeader('Location')
    ? webUtil.absoluteUrl(webUtil.hostname(xhrResponse.responseURL), xhrResponse.getResponseHeader('Location'))
    : xhrResponse.responseURL
```

this change let me move forward but it doesn't check if _Location_ header already has full IRI

**Comment by dmitrizagidulin** [comment]
@elf-pavlik that should work - the `webUtil.absoluteUrl` function passes through an existing absolute iri unchanged.

**Comment by elf-pavlik** [comment]
I could later look at writing a test for that and turn this issue into PR
